# Generated by Django 2.1.7 on 2019-03-05 08:52

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date1', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=20, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=10)),
                ('due_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date1',),
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
