# Generated by Django 2.1.7 on 2019-03-05 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0002_auto_20190305_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
