# Generated by Django 2.1.7 on 2019-03-15 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0006_auto_20190312_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=10, null=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='action',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mblog.Post'),
        ),
    ]
