# Generated by Django 2.1.7 on 2019-03-15 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0007_auto_20190315_0846'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postdetail',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='postdetail',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mblog.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='owner',
            field=models.CharField(default='YH', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
