# Generated by Django 2.1.7 on 2019-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0008_auto_20190315_1154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='postdetail',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='結案'),
        ),
    ]
