# Generated by Django 2.1.7 on 2019-03-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlot',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.Entity', verbose_name='機況'),
        ),
    ]
