# Generated by Django 2.1.7 on 2019-03-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_auto_20190304_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlot',
            options={'ordering': ('-order_no',)},
        ),
    ]
