# Generated by Django 2.1.7 on 2019-03-11 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_auto_20190305_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='current_status',
            field=models.TextField(blank=True, null=True, verbose_name='機況'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity',
            field=models.CharField(max_length=200, verbose_name='機台'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lot_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='批號'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status_history',
            field=models.TextField(blank=True, null=True, verbose_name='歷史機況'),
        ),
    ]
